name: ARC
favicon: null
layout_spectrum: 0.3900086411740631
typography_spectrum: 0.6238420801237226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5431308157276362
  lightness: 0.6301570399664342
  saturation: 0.7400781456381083
  rhythmicContrast: 0.41137680341489613
purpose: []
