name: ARC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87294
title: Aquarius Coin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#f7ea97'
    - '#a5802d'
    - '#aa5500'
    - '#ffff00'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.41137680341489613
purpose: []
